import { Product } from "./types";

export const SampleData: { products: Product[] } = {
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: '59.99',
      brand: 'Polo',
      rating: '4.5',
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Formal White Slim Fit Shirt',
      slug: 'formal-white-slim-fit-shirt',
      category: "Men's Dress Shirts",
      description: 'Elegant white slim fit shirt for formal occasions',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: '49.99',
      brand: 'Arrow',
      rating: '4.2',
      numReviews: 8,
      stock: 12,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      name: 'Casual Checked Shirt',
      slug: 'casual-checked-shirt',
      category: "Men's Casual Shirts",
      description: 'Trendy checked shirt for casual wear',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: '39.99',
      brand: 'Levis',
      rating: '4.0',
      numReviews: 6,
      stock: 15,
      isFeatured: false,
    },
    {
      name: 'Denim Button Down Shirt',
      slug: 'denim-button-down-shirt',
      category: "Men's Casual Shirts",
      description: 'Stylish denim shirt with button-down collar',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: '45.99',
      brand: 'Lee',
      rating: '4.3',
      numReviews: 11,
      stock: 9,
      isFeatured: false,
    },
    {
      name: 'Classic Black Shirt',
      slug: 'classic-black-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless black shirt suitable for all occasions',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: '54.99',
      brand: 'Raymond',
      rating: '4.4',
      numReviews: 14,
      stock: 7,
      isFeatured: false,
    },
    {
      name: 'Light Blue Linen Shirt',
      slug: 'light-blue-linen-shirt',
      category: "Men's Casual Shirts",
      description: 'Comfortable light blue linen shirt perfect for summers',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: '42.99',
      brand: 'Tommy Hilfiger',
      rating: '4.1',
      numReviews: 9,
      stock: 10,
      isFeatured: false,
    },
  ],
};